version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app
files_exists_behavior: overwrite
permissions:
  - object: /home/ubuntu/app/scripts
    pattern: "*.sh"
    mode: 755
    owner: ubuntu
    group: ubuntu
    type:
      - file
  - object: /home/ubuntu/app
    pattern: "**/*"
    owner: ubuntu
    group: ubuntu
    mode: 644
    type:
      - file
  - object: /home/ubuntu/app/docker
    pattern: "**/*"
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - directory
  - object: /home/ubuntu/app/logs
    pattern: "**/*"
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - directory
  - object: /home/ubuntu/app/certbot
    pattern: "**/*"
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - directory
  - object: /home/ubuntu/app/ssl
    pattern: "**/*"
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - directory
  - object: /home/ubuntu/app/.env
    mode: 600
    owner: ubuntu
    group: ubuntu
    type:
      - file
  - object: /home/ubuntu/app/nginx
    pattern: "**/*"
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - directory
  - object: /home/ubuntu/app/nginx/conf.d
    pattern: "**/*"
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - directory
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/set_environment.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 600
      runas: ubuntu
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: ubuntu